# Generated by Django 3.0.3 on 2020-02-13 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscibers',
            options={},
        ),
    ]
