# Generated by Django 3.0.3 on 2020-02-13 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20200213_2032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscibers',
            options={'verbose_name_plural': 'sub'},
        ),
    ]
