# Generated by Django 3.0.3 on 2020-02-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20200213_2114'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscibers',
            new_name='Subsciber',
        ),
        migrations.AlterModelOptions(
            name='subsciber',
            options={'verbose_name_plural': 'Subscribers'},
        ),
    ]
