# Generated by Django 3.0.3 on 2020-02-18 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_auto_20200218_1917'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subsciber',
            new_name='Subscriber',
        ),
    ]
